name: package_flutter_project
description: A Flutter project integrating multiple useful packages.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  faker: ^2.2.0
  intl: ^0.19.0
  convex_bottom_bar: ^3.2.0
  avatar_glow: ^2.0.2
  introduction_screen: ^3.1.11
  lottie: ^2.4.0
  dropdown_search: ^5.0.6
  http: ^1.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/login.json
    - assets/lottie/laptop.json
    - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
